
CFLAGS= -Ofast -pthread -D WITH_AIRSPY -I.  `pkg-config --cflags libairspy`
LIBS= -Ofast -lm -pthread  `pkg-config --libs libairspy` -lusb-1.0 

CC=gcc

all: vortrack

vortrack: airspy.o vor.o vortrack.o
	$(CC) -o vortrack airspy.o vor.o vortrack.o $(LIBS) $(LDFLAGS)

test:	vor.o test.o
	$(CC) -o test vor.o test.o $(LIBS) $(LDFLAGS)

vortrack.o: vortrack.c vortrack.h

clean:
	rm -f *.o vortrack
