CFLAGS=-Ofast -W -D WITH_RTL  -I /usr/local/include/librtlsdr
LIBS= -lusb-1.0 -lrtlsdr -lpthread -L/usr/local/lib -lm


all: vortrack

vortrack: rtl.o vor.o vortrack.o
	$(CC) -o vortrack rtl.o vor.o vortrack.o $(LIBS) $(LDFLAGS)

test:	vor.o test.o
	$(CC) -o test vor.o test.o $(LIBS) $(LDFLAGS)

clean:
	rm -f *.o vortrack
